// Package shellinit generates the shell layer `eval "$(agx shell-init zsh)"`
// installs: an `agx` function that can change the shell's directory for
// `new` / `resume` via the plan-file protocol (spec §10), OSC 7 cwd
// reporting, and the user's configured aliases.
//
// Everything the script does beyond `cd` is delegated back to the binary, so
// the generated code stays small and all logic stays in tested Go.
package shellinit

import (
	"errors"
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/khanakia/agx/internal/appmeta"
)

// Shell names a supported shell.
type Shell string

// Supported shells. bash shares the zsh script (it uses only POSIX-ish
// constructs both accept).
const (
	Zsh  Shell = "zsh"
	Bash Shell = "bash"
)

// Shells is the canonical list.
var Shells = []Shell{Zsh, Bash}

// ErrUnsupported means no script exists for the requested shell.
var ErrUnsupported = errors.New("shellinit: unsupported shell")

// Alias is one generated shell function.
type Alias struct {
	Name string
	// Args are the agx arguments; validated by package config to contain no
	// shell metacharacters, so they are emitted verbatim.
	Args string
}

// Params feeds the template.
type Params struct {
	Shell   Shell
	Aliases []Alias
}

// planCommands are the subcommands routed through the plan-file protocol,
// because they end in a different directory.
var planCommands = []string{"new", "resume"}

var script = template.Must(template.New("init").Parse(`# {{.Name}} shell integration ({{.Shell}}) — generated by ` + "`{{.Name}} shell-init {{.Shell}}`" + `.
# Regenerated on every shell start; edit the config, not this output.
export {{.EnvShellInit}}={{.Shell}}

# Report the cwd to the terminal (OSC 7) so new tabs / splits inherit it.
_{{.Name}}_emit_cwd() {
  printf '\033]7;file://%s%s\033\\' "${HOST:-$(hostname)}" "$PWD"
}

# {{.Name}}: for {{.PlanList}} the binary writes a launch plan instead of
# launching; this function then cd's into the plan's directory (which a child
# process cannot do for its parent shell) and hands the plan back to exec.
{{.Name}}() {
  case "$1" in
    {{.PlanCase}})
      local plan dir rc
      plan=$(mktemp "${TMPDIR:-/tmp}/{{.Name}}-plan.XXXXXX") || return 1
      {{.EnvPlanFile}}="$plan" command {{.Name}} "$@"
      rc=$?
      if [ "$rc" -ne 0 ] || [ ! -s "$plan" ]; then
        command rm -f -- "$plan"
        return "$rc"
      fi
      dir=$(command {{.Name}} exec --plan "$plan" --print-dir) || { command rm -f -- "$plan"; return 1; }
      cd -- "$dir" || { command rm -f -- "$plan"; return 1; }
      _{{.Name}}_emit_cwd
      command {{.Name}} exec --plan "$plan"
      ;;
    *)
      command {{.Name}} "$@"
      ;;
  esac
}
{{range .Aliases}}
{{.Name}}() { {{$.Name}} {{.Args}} "$@"; }{{end}}
`))

// Write renders the script for p.Shell.
func Write(w io.Writer, p Params) error {
	if !supported(p.Shell) {
		return fmt.Errorf("%w %q (supported: %v)", ErrUnsupported, p.Shell, Shells)
	}
	data := struct {
		Name, Shell, EnvShellInit, EnvPlanFile, PlanList, PlanCase string
		Aliases                                                    []Alias
	}{
		Name:         appmeta.Name,
		Shell:        string(p.Shell),
		EnvShellInit: appmeta.EnvShellInit,
		EnvPlanFile:  appmeta.EnvPlanFile,
		PlanList:     strings.Join(planCommands, " / "),
		PlanCase:     strings.Join(planCommands, "|"),
		Aliases:      p.Aliases,
	}
	return script.Execute(w, data)
}

func supported(s Shell) bool {
	for _, v := range Shells {
		if s == v {
			return true
		}
	}
	return false
}
