// Package claude implements provider.Provider for Claude Code: reading the
// OAuth login Claude Code stored per config dir, fetching plan usage, building
// launch / resume commands, listing conversations, and moving history when a
// project folder moves.
//
// It only READS logins. It never refreshes or writes a token, because a
// refresh rotates the refresh token and would log the owning Claude Code
// install out (spec ADR AGX-002).
package claude

import "time"

// Rule: NO BARE STRINGS for any on-disk name, keychain service, env var or
// wire value Claude Code defines. These are Claude Code's own conventions,
// verified against v2.1.281; if a future version renames one, it changes here
// only. Wire values are kept verbatim.

// Binary is the Claude Code executable name.
const Binary = "claude"

// On-disk layout.
const (
	// defaultDirName is the config dir used when CLAUDE_CONFIG_DIR is unset.
	defaultDirName = ".claude"
	// extraDirPrefix marks additional config dirs (~/.claude-work, …); the
	// rest of the name becomes the discovered profile name.
	extraDirPrefix = ".claude-"
	// credentialsFile holds the OAuth token as JSON when Claude Code stores it
	// on disk instead of (or as well as) the keychain.
	credentialsFile = ".credentials.json"
	// profileFile holds account metadata (oauthAccount.emailAddress …). For
	// the default dir it lives one level up, at ~/.claude.json.
	profileFile = ".claude.json"
	// projectsDir holds one sub-dir per working directory, named by
	// EncodePath, each containing <sessionId>.jsonl transcripts.
	projectsDir = "projects"
	// transcriptExt is the transcript file extension.
	transcriptExt = ".jsonl"
)

// configMarkers are entries whose presence makes a ~/.claude-* directory a
// real Claude Code config dir. They exclude look-alikes such as
// ~/.claude-worktrees (git worktrees, not an account).
var configMarkers = []string{"settings.json", projectsDir, credentialsFile, profileFile}

// Environment and keychain.
const (
	// ConfigDirEnv selects a non-default config dir.
	ConfigDirEnv = "CLAUDE_CONFIG_DIR"
	// keychainService is the keychain service name. With CLAUDE_CONFIG_DIR
	// set, Claude Code (v2.1.52+) appends "-" + the first keychainHashLen hex
	// chars of sha256(config dir path); the bare name is the pre-2.1.52 /
	// default-dir entry.
	keychainService = "Claude Code-credentials"
	keychainHashLen = 8
)

// Launch flags.
const resumeFlag = "--resume"

// Credential sources, recorded on Credential.Source for diagnostics.
const (
	SourceFile     = "file"
	SourceKeychain = "keychain"
)

// Usage endpoint.
const (
	// DefaultEndpoint is the usage endpoint Claude Code's /usage calls. It is
	// undocumented and may change shape; parsing is defensive for that reason.
	DefaultEndpoint = "https://api.anthropic.com/api/oauth/usage"
	// oauthBetaHeader opts a request into OAuth bearer auth on
	// api.anthropic.com. Without it the endpoint rejects subscription tokens.
	oauthBetaHeader = "anthropic-beta"
	oauthBetaValue  = "oauth-2025-04-20"
	// userAgent identifies agx in upstream logs.
	userAgent = "agx-cli"
	// maxResponseBytes caps how much of a response body is read. The real
	// payload is ~3 KB.
	maxResponseBytes = 1 << 20
	// snippetMax bounds how much of an error body is echoed into a message.
	snippetMax = 200
)

// DefaultTimeout bounds one usage fetch end to end.
const DefaultTimeout = 15 * time.Second

// Wire kinds of GET /api/oauth/usage limits[].kind.
const (
	kindSession      = "session"
	kindWeeklyAll    = "weekly_all"
	kindWeeklyScoped = "weekly_scoped"
)

// Wire severities of limits[].severity.
const (
	severityNormal  = "normal"
	severityWarning = "warning"
)

// Wire groups of limits[].group.
const (
	groupSession = "session"
	groupWeekly  = "weekly"
)

// Display labels for kinds whose label is not carried in the payload.
const (
	labelSession      = "Current session"
	labelWeeklyAll    = "All models"
	labelScopedFallbk = "Scoped"
	labelOpus         = "Opus"
	labelSonnet       = "Sonnet"
)

// Transcript record types read for conversation listing.
const (
	recordCustomTitle = "custom-title" // set by the user (/rename); preferred
	recordAITitle     = "ai-title"     // generated by Claude Code
)

// Transcript reading bounds. ~/.claude/projects is ~2 GB on a busy machine,
// so files are never read whole: the cwd comes from the head, the title from
// the tail.
const (
	headScanBytes = 256 << 10
	tailScanBytes = 256 << 10
)
